+++
date = "2019-03-26T12:50:40+02:00"
subtitle = ""
tags = []
title = "My Elixir Status 2019"
+++

= Making Elixir Known in France - #MyElixirStatus

== Status of Elixir in France 

(as of begining 2019)

I am currently in France, where Elixir is know only by fellow Functional Programmer.

The Paris meetup is inactive since December 2017.
And the industry (minus some startups) has no idea what so ever can be done with Elixir.

One of the reason is that France, missed the Ruby turn nearly completely exception in a few small startups. (At my big regrets, we are a Java country... pfff...) 

Another reason is that France is stuck with Java since 20 years, ignore other technologies like it's too difficult to learn anything +

== My Solution

I've been waiting for someone in the french IT speaker world, to raise it's voice and start speaking about Elixir in the major IT event but it never came.

This has depressed me enough that I overcame my imposter syndrome and started a "campaign" to make Elixir known in France. (Even so I still think I am not the best to do that... But at least I try).

So I am on a "Tour de France" of conferences, with an Elixir Workshop - 3 hours to discover and start coding with Elixir.

I already given this workshop at 2 major french events since the start of the year :

- Snowcamp : https://sched.co/J2so
- BreizhCamp : https://www.breizhcamp.org/conference/programme/

And I am booked in at least 2 more until summer :

- Devoxx : https://cfp.devoxx.fr/2019/talk/AHP-9443/Decouvrez_pourquoi_Elixir_sera_votre_prochain_langage !
- DevBreak.io : https://app.swapcard.com/widget/event/devbreak19/planning/UGxhbm5pbmdfNTM1Nzg%3D

And I hope to speak at more conference for 2019 !

I've also reactivated the Elixir Paris Meetup, to get the community alive in Paris (that's really a shame... I really should have done that earlier... imposter syndrome...) and the next meetup is the 9th April 2019 !

You can find the info here : https://www.meetup.com/fr-FR/elixir/events/259923641/


== The Workshop

Elixir is a fantastic language and ecosystem built by crafters with testing as central axis.

The language is built on Erlang the only VM able to prove an availability of 99.999999999% over 20 years.

Elixir is at Erlang what Kotlin is in Java.

Nicolas will take you on a tour through the tool, the language and the paradigm (fault tolerance, scalability, hot reload) of the Ecosystem.

pre requisite and workshop are here :

https://github.com/savoisn/elixir-workshop


